#ACS Divisions
#Agricultural & Food Chemistry (AGFD)
#Agrochemicals (AGRO)
#Analytical Chemistry (ANYL)
#Biochemical Technology (BIOT)
#Biological Chemistry (BIOL)
#Business Development & Management (BMGT)
#Carbohydrate Chemistry (CARB)
#Catalysis Science and Technology (CATL)
#Cellulose and Renewable Materials (CELL)
#Chemical Education (CHED)
#Chemical Health & Safety (CHAS)
#Chemical Information (CINF)
#Chemical Toxicology (TOXI)
#Chemistry & the Law (CHAL)
#Colloid & Surface Chemistry (COLL)
#Computers in Chemistry (COMP)
#Energy & Fuels (ENFL)
#Environmental Chemistry (ENVR)
#Fluorine Chemistry (FLUO)
#Geochemistry (GEOC)
#History of Chemistry (HIST)
#Industrial & Engineering Chemistry (I&EC)
#Inorganic Chemistry (DIC) or (INOR)
#Medicinal Chemistry (MEDI)
#Nuclear Chemistry & Technology (NUCL)
#Organic Chemistry (ORGN)
#Physical Chemistry (PHYS)
#Polymer Chemistry (POLY)
#Polymeric Materials: Science & Engineering (PMSE)
#Professional Relations (PROF)
#Rubber (RUBB)
#Small Chemical Businesses (SCHB)
divisions = {'AGFD': {'name': 'agricultural and food chemistry',
  'keywords': ['agricultur*',
   'food',
   'microbiological hazard*',
   'metabolomic*',
   'antibiotic*',
   'breath monitoring',
   'chocolate*',
   'traditional chinese medicine',
   'wine',
   'nut*',
   'allergen*',
   'fresh produce',
   'cereal*',
   'gut microbiome*',
   'biomass',
   'biosensor*',
   'sensory evaluation',
   'endocrine disrupting',
   'ferment*',
   'nanoencapsulation',
   'bioactive',
   'pectin*',
   'beer',
   'spirits',
   'edible',
   'phenolic*',
   'phytochemical*',
   'biopolymer*',
   'nutrition*',
   'microbiome',
   'dietary',
   'fungicide*',
   'huanglongbing',
   'flavor',
   'space travel',
   'extreme environment*',
   'fruit*',
   'tea',
   'cotton',
   'seafood*',
   'nutrient*',
   'artisanal',
   'vegetable*',
   'coffee',
   'cocoa',
   'protein*']},
 'AGRO': {'name': 'agrochemicals',
  'keywords': ['agrochemical',
   'agrochemicals',
   'cannabis',
   'insecticide*',
   'hemp',
   'developing countr*',
   'glyphosate',
   'degradant*',
   'agroecosystem*',
   'pesticide*',
   'soil',
   'microplastic*',
   'stereoisomer*',
   'fumigant*',
   'crop*',
   'pollinator',
   'semiochemical',
   'metabolite*',
   'surface water',
   'groundwater',
   'water sediment interface',
   'habitat protection',
   'herbicide*',
   'neonicotinoid*',
   'xenobiotic*',
   'agricultural emission*',
   'ecotoxicity',
   'veterinary drug*']},
 'ANYL': {'name': 'analytical chemistry',
  'keywords': ['analytical chemistry',
   'spectrometry',
   'analytical separation*',
   'sensor*',
   'nanotechnology',
   'nanozyme*',
   'spectroscopy',
   'biosensing',
   'chemical forensic*',
   'chemometric*',
   'groundwater',
   'chemical identification',
   'bioanaly*',
   'chemical assay*',
   'characterization*',
   'organic analys*',
   'biosensor*',
   'proteomic*',
   'chromatography',
   'blood based diagnostic*',
   'cancer detection']},
 'BIOT': {'name': 'biochemical technology',
  'keywords': ['biochemi*',
   'biotechnology',
   'bioengineering',
   'biomedical technolog*',
   'chemical biology',
   'chromatographic separation*',
   'drug delivery',
   'biotherapeutic*',
   'precision medicine',
   'protein engineering',
   'bioprocess*',
   'systems biology',
   'synthetic biology',
   'biomanufacturing',
   'biophysic*',
   'bio based product*',
   'biological chem*']},
 'BIOL': {'name': 'biological chemistry',
  'keywords': ['biological chemistry',
   'cytochrome*',
   'biomolecule*',
   'bioorthogonal chem*',
   'enzyme chem*',
   'RNA based therap*',
   'bioconjugate',
   'drug discovery',
   'structural biology',
   'chemical signaling',
   'protein folding',
   'protein aggregation',
   'organofluorine',
   'genome engineering',
   'biosynthesis',
   'chem* biology']},
 'BMGT': {'name': 'business development and management',
  'keywords': ['chem* business*',
   'chem* compan*',
   'chem* enterprise*',
   'chem* research and development']},
 'CARB': {'name': 'carbohydrate chemistry',
  'keywords': ['carbohydrate*',
   'oligosaccharide*',
   'glycoconjugate*',
   'glycobiology',
   'glycan*',
   'glycoscience*',
   'protein o-glcnacylation',
   'glycoprotein*',
   'nucleic acid* based therap*',
   'glycomimetics']},
 'CATL': {'name': 'catalysis science and technology',
  'keywords': ['cataly*',
   'electrocataly*',
   'photocataly*',
   'scaling relation*',
   'surface science',
   'surface kinetic*',
   'surface mechanism*',
   'surface reaction*',
   'metal support*',
   'amorphous material*',
   'nanoporous material*',
   'syngas conversion',
   'metal oxides',
   'disordered material*',
   'methane conversion',
   'mixed metal oxide*',
   'vehicle emission control',
   'surface chemistry',
   'material* genome']},
 'CELL': {'name': 'cellulose and renewable materials',
  'keywords': ['cellulose',
   'nanocellulose*',
   'renewable material*',
   'polysaccharide*',
   'colloidal assembl*',
   'lignin',
   'lignocellulos*',
   'hemp']},
 'CHED': {'name': 'chemical education',
  'keywords': ['chem* educat*',
   'data literacy',
   'chem* curricul*',
   'chem* student*',
   'chem* educat*',
   'learn* in the laboratory',
   'climate change literacy',
   'lab* safety',
   'chem* class*',
   'chem* communication*']},
 'CHAS': {'name': 'chemical health and safety',
  'keywords': ['chem* safety',
   'lab* safety',
   'chem* regulations',
   'environmental health and safety']},
 'CINF': {'name': 'chemical information',
  'keywords': ['chemical informatics',
   'bio* modeling',
   'computational chemistry',
   'cheminformatic*',
   'chemical info*',
   'drug discovery',
   'chem* database*',
   'chem* librar*',
   'chem* vocabulary',
   'materials informatic*']},
 'TOXI': {'name': 'chemical toxicology',
  'keywords': ['toxi*', 'antibody drug conjugate*', 'chemical exposure*']},
 'CHAL': {'name': 'chemistry and the law',
  'keywords': ['chem* patent*',
   'pharmaceutical patent*',
   'chem* in commerce']},
 'COLL': {'name': 'colloid and surface chemistry',
  'keywords': ['colloid*',
   'surface chemistry',
   'surface science',
   'surfactant*',
   'biomaterial*',
   'biointerface*',
   'nanomaterial*',
   'coating material*',
   'biomembrane*',
   'nanoparticle*',
   'polymer system*',
   'adsorption',
   'surface reaction*',
   'tribolog*',
   'nanomedicine*',
   'low dimensional material*',
   'molecular electronic*',
   'mechanochem*',
   'tribochem*',
   'emuls*',
   'nanotheranostic*',
   'coacerv*',
   'nanostructure',
   'monolayer*',
   'bilayer*',
   'thin film*']},
 'COMP': {'name': 'computers in chemistry',
  'keywords': ['chem* comput*',
   'drug design',
   'drug discovery',
   'computational chem*',
   'molecular mechanics',
   'multiscale modeling',
   'computational quantum chem*',
   'quantum comp*',
   'quantum dynamic*',
   'multiscale computational modeling',
   'computational model* of chem*',
   'chem* database*',
   'material* database*',
   'protein database*',
   'rna design*',
   'density functional theory',
   'computational cataly*',
   'molecular model*',
   'chem* librar*',
   'chem* screen*',
   'molecular recognition',
   'computer-aided peptide design']},
 'ENFL': {'name': 'energy and fuels',
  'keywords': ['energy and fuel*',
   'energy application*',
   'fuel*',
   'hydrocracking',
   'hydrotreating',
   'waste feedstock*',
   'energy technolog*',
   '*material* for energy',
   'gas separation*',
   'gas storage',
   'gas utilization',
   'hybrid solar cell*',
   'fuel* design',
   'aviation fuel*',
   'hydraulic frac*',
   'batter*',
   'bioenergy',
   'petroleum',
   'methane',
   'natural gas*',
   'lithium ion',
   'resource recovery',
   'energy conversion*',
   'hybrid energy',
   'porous material*',
   'environment* sustain*',
   'photocataly*',
   'biofuel*',
   'bio based product*',
   'energy material*',
   'carbon dioxide conversion',
   'carbon dioxide utilization',
   'renewable energy',
   'energy storage',
   'electrochemical',
   'solar energy',
   'artificial photosynthesis',
   'resource production',
   'oil industry',
   'gas industry',
   'oil and gas industry',
   'fuel cell*',
   'hybrid vehicle*',
   'cataly*',
   'solar cell',
   'water splitting',
   'hydrogen generation',
   'gas hydrate*',
   'shale gas',
   'energy efficiency',
   'bio based chemical*',
   'hydrogen energy',
   'carbon management',
   'geothermal energy']},
 'ENVR': {'name': 'environmental chemistry',
  'keywords': ['environmental chem*',
   'atmospher* chem*',
   'biomimetic membrane*',
   'cataly*',
   'water treatment',
   'water purification',
   'plastic* recycling',
   'emerging contaminant*',
   'disinfection byproduct*',
   'environmental health',
   'two dimensional nanomaterial*',
   'environmental implication*',
   'water quality',
   'water distribution',
   'water infrastructure',
   'water pollution',
   'agricultural waste*',
   'environmental monitor*',
   'environmental remediation*',
   'nanomaterial* in the environment',
   'environmental science',
   'biogeochemical transformation',
   'water contaminant*',
   'environment* research',
   'green chem*',
   'environmental bioprocess*',
   'micro plastic*',
   'stormwater',
   'environmental sustainability',
   'water channel*',
   'water purification',
   'water desalination',
   'biochar',
   'hydrochar',
   'water sustainability',
   'water analysis',
   'wastewater',
   'dissolved organic matter',
   '*sensor*',
   'green infrastructure',
   'soil*',
   'nanotechnology',
   'photooxidation',
   'water source*',
   'fertilizer*',
   'drinking water',
   'organic contaminant*',
   'microplastic pollution',
   'nanobubble*',
   'separation of salt*',
   'radionuclide*',
   'trace organic contaminant*',
   'soil plant system*',
   'nanotoxicology',
   'clay mineral*',
   'pesticides in surface water']},
 'FLUO': {'name': 'fluorine chemistry',
  'keywords': ['fluorine*', 'radiopharmaceutical chem*']},
 'GEOC': {'name': 'geochemistry',
  'keywords': ['*geochem*',
   'iron oxide*',
   'inorganic solid*',
   'oil and gas development',
   'manganese oxide*',
   'contaminated soil',
   'groundwater',
   'geogenic',
   'anthropogenic',
   'clathrate hydrate',
   'geological process*',
   'mineral dissolution',
   'contaminated site remediation',
   'biomineralization',
   'hydraulic frac*',
   'soil ecosystem*',
   'unconventional oil and gas development',
   'cementitious material*']},
 'HIST': {'name': 'history of chemistry',
  'keywords': ['chem* histor*', 'history of chem*', 'evolution of chem*']},
 'I&EC': {'name': 'industrial and engineering chemistry',
  'keywords': ['industrial and engineering chemistry',
   'industrial chem*',
   'molten salt*',
   'recycling material*',
   'material* recovery',
   'water desalination',
   'rare earth element*',
   'chem* industrial application*',
   'separation science*',
   'water purification',
   'industrial and engineering chemistry']},
 'INOR': {'name': 'inorganic chemistry',
  'keywords': ['*inorganic chem*',
   'organometallic*',
   'phosphorus chem*',
   'metallodrug*',
   '*inorganic cataly*',
   'chemistry of material*',
   'metal organic framework*',
   'nanomaterial*',
   'coordination chem*',
   'electrochem*',
   'lanthanide*',
   'actinide*',
   'electrocataly*',
   'nanoscience*',
   'metal nanostructure*',
   'solid state phenomen*']},
 'MEDI': {'name': 'medicinal chemistry',
  'keywords': ['medic* chem*',
   'drug discovery',
   'immunomodulator*',
   'lipophil*',
   'protein degradation',
   'sulfonamide*',
   'glioblastoma*',
   'pancreatic cancer',
   'drug design',
   'protein interaction*',
   'neurodegeneration',
   'targeting rna',
   'brain penetration',
   'neuro-oncology',
   'opioid epidemic',
   'gasotransmitter*',
   'pi3k inhibitor*',
   'atropisomer*',
   'cyp450 enzyme*',
   'muscarinic receptor*',
   'hiv 1 infection',
   'neuropathic pain',
   'antibiotic*',
   'kinase inhibitor*',
   'macrocycle*',
   'cyclopeptide*',
   'misfolded protein*']},
 'NUCL': {'name': 'nuclear chemistry and technology',
  'keywords': ['nuclear tech*',
   'nuclear chem*',
   'actinide*',
   'radiochem*',
   'nuclear waste',
   'nuclear forensic*',
   'radioisotope*',
   'nuclear fuel*',
   'lanthanide*',
   'radiotherapeutic*',
   'nuclear reaction*',
   'molten salt reactor*',
   'concentrated electrolyte*',
   'nuclear medicine*',
   'isotope*',
   'accelerator facilit*',
   'curium',
   'nuclear fission']},
 'ORGN': {'name': 'organic chemistry',
  'keywords': ['organic chem*',
   'organic synthes*',
   'asymmetric reaction*',
   'asymmetric synthes*',
   'biocataly*',
   'carbon allotrope*',
   'cross coupling reaction*',
   'heterocycle*',
   'aromatic*',
   'organic electrochem*',
   'molecular recognition',
   'molecular self assembly',
   'organometallic*',
   'peptide*',
   'protein*',
   'amino acid*',
   'photoredox',
   'complex molecule*',
   'enzyme engineering',
   'synthetic chem*',
   'organic molecule*',
   'polymer chem*',
   'carbon nanotube* chem*',
   'graphene chem*',
   'organic electronic*',
   'amide bond*',
   'chemical biology']},
 'PHYS': {'name': 'physical chemistry',
  'keywords': ['physical chem*',
   'nonlinear optic*',
   'electrochem*',
   'biomolecular structure*',
   'biomolecular dynamic*',
   'biophysic*',
   'ion*',
   '2d material*',
   'two dimensional material*',
   'amyloid',
   'graph theory',
   'molecular electronic*',
   'optical imaging',
   'electro*',
   'materials for energy',
   'molecular assembl*',
   'biomaterial*',
   'biomolecular structure*',
   'microscopy',
   'spectroscopy',
   'redox flow batter*',
   'computational molecular science',
   'exciton*',
   'astrochem*',
   'density functional theory',
   'chiral*',
   'nano*',
   'enzyme specificity',
   'enzyme promiscuity',
   'liquid theory',
   'membrane protein*',
   'molecular fluid*',
   'photoactivit*',
   'atom*',
   'quantum*']},
 'POLY': {'name': 'polymer chemistry',
  'keywords': ['polymer*',
   'polyolefin*',
   'biomacromolecule*',
   'macromolecule*',
   'plastic*',
   'polymeriz*',
   'polymeric',
   'block copolymer*',
   'poly 2 oxazoline*',
   'biomimicry',
   'lignin']},
 'PMSE': {'name': 'polymeric materials: science and engineering',
  'keywords': ['polymer* material*',
   'polymer* science',
   '*polymer*',
   'coating material*',
   'thin film*',
   'polyolefin*',
   'macromolecul*',
   'tissue engineering',
   '*peptide*',
   'nanoclay*',
   'polyelectrolyte*',
   'polyphosphazene*']},
 'PROF': {'name': 'professional relations', 'keywords': ['chem* education']},
 'RUBB': {'name': 'rubber', 'keywords': ['rubber*']},
 'SCHB': {'name': 'small chemical businesses',
  'keywords': ['chem* sector*',
   'academic entrepreneur*',
   'commercial chem*',
   'science advoca*']}}